# Generated by Django 3.2.16 on 2025-01-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('currency', models.CharField(default='RUR', max_length=10, verbose_name='Валюта')),
                ('experience', models.CharField(blank=True, max_length=100, verbose_name='Опыт')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки')),
                ('area', models.CharField(max_length=100, verbose_name='Регион')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
